title: "ytggobs's website"
description: "Website for ytggobs's projects"
author: ytggobs
url: https://ytggobs.netlify.app/

markdown: kramdown
theme: just-the-doc

exclude:
  - "*.html"
  - "*.css"
  - README.md